# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: detect_model.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12\x64\x65tect_model.proto\"H\n\x0cImageWithOss\x12\x10\n\x08img_path\x18\x01 \x01(\t\x12\x13\n\x0b\x62ucket_name\x18\x02 \x01(\t\x12\x11\n\tclient_ip\x18\x03 \x01(\t\":\n\x05Image\x12\x10\n\x08img_name\x18\x01 \x01(\t\x12\x0c\n\x04\x64\x61ta\x18\x02 \x01(\x0c\x12\x11\n\tclient_ip\x18\x03 \x01(\t\"t\n\x15\x44\x65tectedResultWithOss\x12\x0f\n\x07imgName\x18\x01 \x01(\t\x12\x0b\n\x03tag\x18\x02 \x03(\t\x12\x17\n\x06\x63orner\x18\x03 \x03(\x0b\x32\x07.Corner\x12\x10\n\x08\x61\x63\x63uracy\x18\x04 \x03(\x01\x12\x12\n\nresultPath\x18\x05 \x01(\t\"Y\n\x0e\x44\x65tectedResult\x12\x0f\n\x07imgName\x18\x01 \x01(\t\x12\x0b\n\x03tag\x18\x02 \x03(\t\x12\x17\n\x06\x63orner\x18\x03 \x03(\x0b\x32\x07.Corner\x12\x10\n\x08\x61\x63\x63uracy\x18\x04 \x03(\x01\"8\n\x06\x43orner\x12\n\n\x02x1\x18\x01 \x01(\x01\x12\n\n\x02y1\x18\x02 \x01(\x01\x12\n\n\x02x2\x18\x03 \x01(\x01\x12\n\n\x02y2\x18\x04 \x01(\x01\x32h\n\x0b\x44\x65tectModel\x12!\n\x06\x64\x65tect\x12\x06.Image\x1a\x0f.DetectedResult\x12\x36\n\rdetectWithOss\x12\r.ImageWithOss\x1a\x16.DetectedResultWithOssb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'detect_model_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_IMAGEWITHOSS']._serialized_start=22
  _globals['_IMAGEWITHOSS']._serialized_end=94
  _globals['_IMAGE']._serialized_start=96
  _globals['_IMAGE']._serialized_end=154
  _globals['_DETECTEDRESULTWITHOSS']._serialized_start=156
  _globals['_DETECTEDRESULTWITHOSS']._serialized_end=272
  _globals['_DETECTEDRESULT']._serialized_start=274
  _globals['_DETECTEDRESULT']._serialized_end=363
  _globals['_CORNER']._serialized_start=365
  _globals['_CORNER']._serialized_end=421
  _globals['_DETECTMODEL']._serialized_start=423
  _globals['_DETECTMODEL']._serialized_end=527
# @@protoc_insertion_point(module_scope)
