# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import detect_model_pb2 as detect__model__pb2


class DetectModelStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.detect = channel.unary_unary(
                '/DetectModel/detect',
                request_serializer=detect__model__pb2.Image.SerializeToString,
                response_deserializer=detect__model__pb2.DetectedResult.FromString,
                )
        self.detectWithOss = channel.unary_unary(
                '/DetectModel/detectWithOss',
                request_serializer=detect__model__pb2.ImageWithOss.SerializeToString,
                response_deserializer=detect__model__pb2.DetectedResultWithOss.FromString,
                )


class DetectModelServicer(object):
    """Missing associated documentation comment in .proto file."""

    def detect(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def detectWithOss(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DetectModelServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'detect': grpc.unary_unary_rpc_method_handler(
                    servicer.detect,
                    request_deserializer=detect__model__pb2.Image.FromString,
                    response_serializer=detect__model__pb2.DetectedResult.SerializeToString,
            ),
            'detectWithOss': grpc.unary_unary_rpc_method_handler(
                    servicer.detectWithOss,
                    request_deserializer=detect__model__pb2.ImageWithOss.FromString,
                    response_serializer=detect__model__pb2.DetectedResultWithOss.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'DetectModel', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class DetectModel(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def detect(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/DetectModel/detect',
            detect__model__pb2.Image.SerializeToString,
            detect__model__pb2.DetectedResult.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def detectWithOss(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/DetectModel/detectWithOss',
            detect__model__pb2.ImageWithOss.SerializeToString,
            detect__model__pb2.DetectedResultWithOss.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
